name: VaultTax
version: '1.0-SNAPSHOT'
main: VaultTax.VaultTaxMain
api-version: 1.18
commands:
  spigui:
    description: Your description
    usage: /<command>

  paytaxes:
      description: Your description
      usage: /<command>
